import {
  PiHouseDuotone,
  PiUserDuotone,
  PiBuildingsDuotone,
  PiHeartDuotone,
  PiMegaphoneDuotone,
} from "react-icons/pi";

export const navData = [
  { name: "الرئيسية", path: "/", icone: <PiHouseDuotone /> },
  { name: "العقارات", path: "/buildings", icone: <PiBuildingsDuotone /> },
  { name: "حسابي", path: "/account", icone: <PiUserDuotone /> },
  { name: "المفضلة", path: "/love", icone: <PiHeartDuotone /> },
  { name: "مطلوب", path: "/requests", icone: <PiMegaphoneDuotone /> },
];
export const MobData = [
  { name: "حسابي", path: "/account", icone: <PiUserDuotone /> },
  { name: "العقارات", path: "/buildings", icone: <PiBuildingsDuotone /> },
  { name: "الرئيسية", path: "/", icone: <PiHouseDuotone /> },
  { name: "المفضلة", path: "/love", icone: <PiHeartDuotone /> },
  { name: "مطلوب", path: "/requests", icone: <PiMegaphoneDuotone /> },
];
export const Imag = [
  { name: "/home/building.png" },
  { name: "/home/psd.jpg" },
  { name: "/home/land.jpg" },
  { name: "/home/rr.png" },
  { name: "/home/we.png" },
];

export const house = [
  {
    img: "/home/psd.jpg",
    title: "شقة سكنية",
    discrep: "شقة سكنية مجهز بافضل الخدمات وبتصميم مميز",
    prise: "450K ل.س",
    link: "/buildings/flat",
    display: "للإجار",
    location_x: "34.6985",
    location_y: "36.7237",
  },
  {
    img: "/home/rr.png",
    title: "منزل",
    discrep: "منزل مجهز بافضل الخدمات وبتصميم مميز",
    prise: "210M ل.س",
    link: "/buildings/house",
    display: "للبيع",
    location_x: "32.6285",
    location_y: "36.7357",
  },
  {
    img: "/home/store.jpg",
    title: "محل تجاري ",
    discrep: "محل تجاري مجهز وعلى شارع رئيسي ",
    prise: "1M ل.س",
    link: "/buildings/store",
    display: "للإجار",
    location_x: "34.6965",
    location_y: "36.2437",
  },
  {
    img: "/home/land.jpg",
    title: "أرض سكنية ",
    discrep: "أرض سكنية طابو أخضر ",
    prise: "120M ل.س",
    link: "/buildings/land",
    display: "للبيع",
    location_x: "35.6985",
    location_y: "36.7137",
  },
];

export const hom = [
  { name: "منازل" },
  { name: "شقق" },
  { name: "محال تجارية" },
  { name: "أراضي" },
  { name: "محاضر" },
  { name: "أبراج" },
];

export const whyus = [
  {
    title: "تفاصيل شاملة",
    discrep:
      "يمكنك ان تتعرف على مافة التفاصيل الخاصة بالعقار الذي تبحث عنه بداية من المساحةوعدد الغرف والسعر وقيمة القسط الشهري  وموعد الاستلام",
  },
  {
    title: "سهولة الاستخدام",
    discrep:
      "يمكنك ان  تختار ترتيب العقارات وفقا للاقل سعرا او لاطول فترة سداد ممكنةاو الحاهزة للسكن وغيرها  من التفاصيل التي تحتاج اليها ",
  },
  {
    title: "حجز مباشر",
    discrep: "يمكنك ان تقوم بحجز وحدتك عبر الموقع الالكتروني بضغطة واحدة",
  },
  {
    title: "أماكن مميزة",
    discrep: "يمكنك البحث عن العقار في المناطق التي تفضل السكن فيها",
  },
];

export const houses = [
  {
    img: "/home/psd.jpg",
    title: "شقة سكنية",
    discrep: "شقة سكنية مجهز بافضل الخدمات وبتصميم مميز",
    prise: "450K ل.س",
    link: "/buildings/flat",
    type: "flat",
    display: "للبيع",
    location_x: "34.4985",
    location_y: "36.7237",
  },
  {
    img: "/home/rr.png",
    title: "منزل",
    discrep: "منزل مجهز بافضل الخدمات وبتصميم مميز",
    prise: "210M ل.س",
    link: "/buildings/house",
    type: "house",
    display: "للإجار",
    location_x: "34.6682",
    location_y: "36.7234",
  },
  {
    img: "/home/store.jpg",
    title: "محل تجاري ",
    discrep: "محل تجاري مجهز وعلى شارع رئيسي ",
    prise: "1M ل.س",
    link: "/buildings/store",
    type: "store",
    display: "للإجار",
    location_x: "34.6985",
    location_y: "36.7235",
  },
  {
    img: "/home/land.jpg",
    title: "أرض سكنية ",
    discrep: "أرض سكنية طابو أخضر ",
    prise: "120M ل.س",
    link: "/buildings/land",
    type: "land",
    display: "للبيع",
    location_x: "34.6975",
    location_y: "36.7237",
  },
  {
    img: "/home/building.png",
    title: "محضر سكني ",
    discrep: "محضر سكني جاهز للسكن شجميع الشقق مكسية ",
    prise: "2.100M ل.س",
    link: "/buildings/building",
    type: "building",
    display: "للبيع",
    location_x: "34.6285",
    location_y: "36.7237",
  },
  {
    img: "/home/psd.jpg",
    title: "شقة سكنية",
    discrep: "شقة سكنية مجهز بافضل الخدمات وبتصميم مميز",
    prise: "450K ل.س",
    link: "/buildings/flat",
    type: "flat",
    display: "للبيع",
    location_x: "34.6932",
    location_y: "36.7237",
  },
  {
    img: "/home/rr.png",
    title: "منزل",
    discrep: "منزل مجهز بافضل الخدمات وبتصميم مميز",
    prise: "210M ل.س",
    link: "/buildings/house",
    type: "house",
    display: "للإجار",
    location_x: "34.6985",
    location_y: "36.7231",
  },
  {
    img: "/home/store.jpg",
    title: "محل تجاري ",
    discrep: "محل تجاري مجهز وعلى شارع رئيسي ",
    prise: "1M ل.س",
    link: "/buildings/store",
    type: "store",
    display: "للإجار",
    location_x: "32.6985",
    location_y: "36.7237",
  },
  {
    img: "/home/land.jpg",
    title: "أرض سكنية ",
    discrep: "أرض سكنية طابو أخضر ",
    prise: "120M ل.س",
    link: "/buildings/land",
    type: "land",
    display: "للبيع",
    location_x: "34.6245",
    location_y: "36.7237",
  },
  {
    img: "/home/building.png",
    title: "محضر سكني ",
    discrep: "محضر سكني جاهز للسكن شجميع الشقق مكسية ",
    prise: "2.100M ل.س",
    link: "/buildings/building",
    type: "building",
    display: "للبيع",
    location_x: "34.6915",
    location_y: "36.7237",
  },
  {
    img: "/home/psd.jpg",
    title: "شقة سكنية",
    discrep: "شقة سكنية مجهز بافضل الخدمات وبتصميم مميز",
    prise: "450K ل.س",
    link: "/buildings/flat",
    type: "flat",
    display: "للبيع",
    location_x: "34.6985",
    location_y: "36.7337",
  },
  {
    img: "/home/rr.png",
    title: "منزل",
    discrep: "منزل مجهز بافضل الخدمات وبتصميم مميز",
    prise: "210M ل.س",
    link: "/buildings/house",
    type: "house",
    display: "للإجار",
    location_x: "34.6985",
    location_y: "32.7237",
  },
  {
    img: "/home/store.jpg",
    title: "محل تجاري ",
    discrep: "محل تجاري مجهز وعلى شارع رئيسي ",
    prise: "1M ل.س",
    link: "/buildings/store",
    type: "store",
    display: "للإجار",
    location_x: "34.6385",
    location_y: "36.7237",
  },
  {
    img: "/home/land.jpg",
    title: "أرض سكنية ",
    discrep: "أرض سكنية طابو أخضر ",
    prise: "120M ل.س",
    link: "/buildings/land",
    type: "land",
    display: "للبيع",
    location_x: "34.6922",
    location_y: "36.7237",
  },
  {
    img: "/home/building.png",
    title: "محضر سكني ",
    discrep: "محضر سكني جاهز للسكن شجميع الشقق مكسية ",
    prise: "2.100M ل.س",
    link: "/buildings/building",
    type: "building",
    display: "للبيع",
    location_x: "34.2985",
    location_y: "36.7237",
  },
];

export const HouseInfo = [
  {
    title: "منزل",
    discrep: "منزل مجهز بافضل الخدمات وبتصميم مميز",
    numRoom: "3",
    size: "105",
    direction: "غربي",
    numFloor: "1",
    sizeGarden: "30",
    prise: "210.000.000",
    display: "للبيع",
    place: "حمص - الوعر",
    images: [
      "/home/rr.png",
      "/home/psd.jpg",
      "/home/building.png",
      "/home/land.jpg",
      "/home/store.jpg",
    ],
    seller: "مكتب النور",
    imageSeller: "/6.png",
    sellerNum: "00963945866342",
  },
];
export const FlatInfo = [
  {
    title: "شقة سكنية",
    discrep: "شقة سكنية مجهز بافضل الخدمات وبتصميم مميز",
    type: "flat",
    numRoom: "2",
    size: "90",
    direction: "شرقي",
    numFloor: "3",
    prise: "450.000",
    display: "للإجار",
    place: "دمشق - دوما",
    images: [
      "/home/rr.png",
      "/home/psd.jpg",
      "/home/building.png",
      "/home/land.jpg",
      "/home/store.jpg",
    ],
    seller: "أحمد سعيد",
    imageSeller: "/6.png",
    sellerNum: "00963945865342",
    location_x: "34.6985",
    location_y: "36.7237",
  },
];
export const StoreInfo = [
  {
    title: "محل تجاري",
    discrep: "محل تجاري مجهز وعلى شارع رئيسي",
    size: "50",
    direction: "جنوبي",
    prise: "1.000.000",
    display: "للإجار",
    place: "دمشق - مزة86",
    images: [
      "/home/store.jpg",
      "/home/rr.png",
      "/home/psd.jpg",
      "/home/building.png",
      "/home/land.jpg",
    ],
    seller: "مكتب الإخلاص",
    imageSeller: "/6.png",
    sellerNum: "00963937785439",
  },
];
export const LandInfo = [
  {
    title: "أرض سكنية",
    discrep: "أرض سكنية طابو أخضر",
    size: "470",
    prise: "120.000.000",
    display: "للبيع",
    place: "حمص - الأوراس",
    images: [
      "/home/land.j pg",
      "/home/rr.png",
      "/home/psd.jpg",
      "/home/building.png",
      "/home/store.jpg",
    ],
    seller: "Mohammad Ahmad",
    imageSeller: "/6.png",
    sellerNum: "00963937785439",
  },
];
export const BuildingInfo = [
  {
    title: "محضر سكني",
    discrep: "محضر سكني جاهز للسكن شجميع الشقق مكسية",
    numFlat: "6",
    FlatSize: "100",
    direction: "غربي",
    numFloor: "3",
    prise: "2.100.000.000",
    display: "للبيع",
    place: "حمص - الوعر",
    images: [
      "/home/building.png",
      "/home/rr.png",
      "/home/psd.jpg",
      "/home/land.jpg",
      "/home/store.jpg",
    ],
    seller: "مكتب النور",
    imageSeller: "/6.png",
    sellerNum: "00963945866342",
  },
];
export const UserInfo = [
  {
    name: "Ahmad Tarek",
    phone: "00963996742843",
    facebook: "https://www.facebook.com/",
    instagram: "https://www.instagram.com/",
    telegram: "https://t.me/",
    image: "/user.png",
  },
];

export const add = [
  {
    title: "منزل للإجار",
    discrep: "بحاجة منزل للإجار غرفتين مساحة 90 متر مربع",
    minPrice: "500 ل.س",
    maxPrice: "800 ل.س",
    display: "للإجار",
  },
  {
    title: "شقة للبيع",
    discrep: "بحاجة شقة للسكن 3 غرف تجهيز ممتاز ",
    minPrice: "150M ل.س",
    maxPrice: "210M ل.س",
    display: "للييع",
  },
  {
    title: "منزل للرهن",
    discrep: "بحاجة منزل للرهن غرفتين",
    minPrice: "70M ل.س",
    maxPrice: "79M ل.س",
    display: "للرهن",
  },
];

export const nots = [
  {
    title: "شقة  جديدة",
    discrep: "تم اضافة شقة  جديدة ",
    time: "10:02 2024/3/10 ",
    link: "/buildings/flat",
  },
  {
    title: "منزل جديد",
    discrep: "تم اضافة منزل جديد ",
    time: "09:13 2024/3/10 ",
    link: "/buildings/house",
  },
  {
    title: "محل  جديد",
    discrep: "تم اضافة محل  جديد ",
    time: "12:40 2024/3/9 ",
    link: "/buildings/store",
  },
  {
    title: "أرض  جديدة",
    discrep: "تم اضافة أرض  جديدة ",
    time: "05:35 2024/3/4 ",
    link: "/buildings/land",
  },
  {
    title: "محضر  جديد",
    discrep: "تم اضافة محضر  جديد ",
    time: "11:09 2024/3/3 ",
    link: "/buildings/building",
  },
  {
    title: "منزل جديد",
    discrep: "تم اضافة منزل جديد ",
    time: "01:12 2024/3/2 ",
    link: "/buildings/house",
  },
];
