import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Sidpar from "./components/Sidpar";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      {/* تحديد أيقونة الموقع هنا */}
      <link rel="icon" href="/icon.png" />
    </Head>
    <body className={inter.className}>
      <div>
        {/* <Header /> */}
        <Sidpar />
        <div className="wrapper min-h-[100vh] xl:min-h-[92vh] py-10 xl:pr-20 xl:pt-10">
          {children}
          <Analytics />
        </div>
        <Footer />
      </div>
    </body>
  </html>
  );
}
